
name: Scala CI

on:
  push:
    branches: [ "main" ]
    paths:
    - src/**
    - testData/**
    - build.sbt
    - project/**
  pull_request:
    branches: [ "main" ]
    paths:
    - src/**
    - testData/**
    - build.sbt
    - project/**

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: sbt

    - name: Setup SBT Launcher
      uses: sbt/setup-sbt@v1
              
    - name: Build and Test
      run: sbt -v test
      
      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@v2
